import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { ClerkProvider, currentUser, SignedIn } from "@clerk/nextjs";
import { Nav } from "@/components/shared/Nav";
import { ThemeProvider } from "@/providers/theme-provider";
import BgPattern from "@/components/shared/bgPattern";
import Footer from "@/components/shared/footer";
import { init } from "next/dist/compiled/webpack/webpack";
import { initialUser } from "@/lib/init-user";
import { redirect } from "next/navigation";
import { ModelProvider } from "@/providers/model-provider";

const inter = Cairo({ subsets: ["arabic"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      
    >


      <html lang="ar" dir="rtl">

        <body
          className="min-h-[70vh] scrollbar-hide"
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Nav isAdmin='dd' />
            <BgPattern />
            <ModelProvider />


            {children}

          </ThemeProvider>
        </body>
        <Footer />
      </html>
    </ClerkProvider>
  );
}
